config/routes.rb
Rails.application.routes.draw do
  resources :cut_elaborateds
  resources :elaborated_product_names
  resources :mature_cuts
  resources :cuts
  resources :cut_names
  resources :pieces
  resources :piece_names
  resources :quarterings
  resources :channels
  resources :suppliers
  resources :families
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :family
  belongs_to :supplier
  belongs_to :user
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :piece
  belongs_to :cut_name
  has_one :mature_cut
  has_one :cut_elaborated

  def process
    case self.processing_type
    when 'MatureCut'
      self.mature_cut
    when 'CutElaborated'
      self.cut_elaborated
    when 'FinalCut'
      self
    else
      nil
    end
  end
end

app/models/cut_elaborated.rb
class CutElaborated < ApplicationRecord
  belongs_to :cut
  belongs_to :elaborated_product_name

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/cut_name.rb
class CutName < ApplicationRecord
  belongs_to :piece
end

app/models/elaborated_product_name.rb
class ElaboratedProductName < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/mature_cut.rb
class MatureCut < ApplicationRecord
  belongs_to :cut

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  delegate :name, to: :piece_name

  belongs_to :quartering
  belongs_to :piece_name
end

app/models/piece_name.rb
class PieceName < ApplicationRecord
  belongs_to :family
end

app/models/quartering.rb
class Quartering < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/elaborated_product_names_controller.rb
class ElaboratedProductNamesController < ApplicationController
  before_action :set_elaborated_product_name, only: %i[ show edit update destroy ]

  # GET /elaborated_product_names or /elaborated_product_names.json
  def index
    @elaborated_product_names = ElaboratedProductName.all
  end

  # GET /elaborated_product_names/1 or /elaborated_product_names/1.json
  def show
  end

  # GET /elaborated_product_names/new
  def new
    @elaborated_product_name = ElaboratedProductName.new(cut_id: params[:cut_id])
  end

  # GET /elaborated_product_names/1/edit
  def edit
  end

  # POST /elaborated_product_names or /elaborated_product_names.json
  def create
    @elaborated_product_name = ElaboratedProductName.new(elaborated_product_name_params)

    respond_to do |format|
      if @elaborated_product_name.save
        format.html { redirect_to elaborated_product_name_url(@elaborated_product_name), notice: "Elaborated product name was successfully created." }
        format.json { render :show, status: :created, location: @elaborated_product_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elaborated_product_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elaborated_product_names/1 or /elaborated_product_names/1.json
  def update
    respond_to do |format|
      if @elaborated_product_name.update(elaborated_product_name_params)
        format.html { redirect_to elaborated_product_name_url(@elaborated_product_name), notice: "Elaborated product name was successfully updated." }
        format.json { render :show, status: :ok, location: @elaborated_product_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elaborated_product_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elaborated_product_names/1 or /elaborated_product_names/1.json
  def destroy
    @elaborated_product_name.destroy

    respond_to do |format|
      format.html { redirect_to elaborated_product_names_url, notice: "Elaborated product name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elaborated_product_name
      @elaborated_product_name = ElaboratedProductName.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elaborated_product_name_params
      params.require(:elaborated_product_name).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/cut_names_helper.rb
module CutNamesHelper
end

app/helpers/cuts_helper.rb
module CutsHelper
end

app/helpers/elaborated_product_names_helper.rb
module ElaboratedProductNamesHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/elaborated_product_names/_elaborated_product_name.html.erb
<div id="<%= dom_id elaborated_product_name %>">
  <p>
    <strong>Name:</strong>
    <%= elaborated_product_name.name %>
  </p>

</div>

app/views/elaborated_product_names/_form.html.erb
<%= form_with(model: elaborated_product_name) do |form| %>
  <% if elaborated_product_name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(elaborated_product_name.errors.count, "error") %> prohibited this elaborated_product_name from being saved:</h2>

      <ul>
        <% elaborated_product_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/elaborated_product_names/edit.html.erb
<h1>Editing elaborated product name</h1>

<%= render "form", elaborated_product_name: @elaborated_product_name %>

<br>

<div>
  <%= link_to "Show this elaborated product name", @elaborated_product_name %> |
  <%= link_to "Back to elaborated product names", elaborated_product_names_path %>
</div>

app/views/elaborated_product_names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Elaborated product names</h1>

<div id="elaborated_product_names">
  <% @elaborated_product_names.each do |elaborated_product_name| %>
    <%= render elaborated_product_name %>
    <p>
      <%= link_to "Show this elaborated product name", elaborated_product_name %>
    </p>
  <% end %>
</div>

<%= link_to "New elaborated product name", new_elaborated_product_name_path %>

app/views/elaborated_product_names/new.html.erb
<h1>New elaborated product name</h1>

<%= render "form", elaborated_product_name: @elaborated_product_name %>

<br>

<div>
  <%= link_to "Back to elaborated product names", elaborated_product_names_path %>
</div>

app/views/elaborated_product_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @elaborated_product_name %>

<div>
  <%= link_to "Edit this elaborated product name", edit_elaborated_product_name_path(@elaborated_product_name) %> |
  <%= link_to "Back to elaborated product names", elaborated_product_names_path %>

  <%= button_to "Destroy this elaborated product name", @elaborated_product_name, method: :delete %>
</div>