config/routes.rb
Rails.application.routes.draw do
  resources :cut_elaborateds
  resources :elaborated_product_names
  resources :mature_cuts
  resources :cuts
  resources :cut_names
  resources :pieces
  resources :piece_names
  resources :quarterings
  resources :channels
  resources :suppliers
  resources :families
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :family
  belongs_to :supplier
  belongs_to :user
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :piece
  belongs_to :cut_name
  has_one :mature_cut
  has_one :cut_elaborated

  def process
    case self.processing_type
    when 'MatureCut'
      self.mature_cut
    when 'CutElaborated'
      self.cut_elaborated
    when 'FinalCut'
      self
    else
      nil
    end
  end
end

app/models/cut_elaborated.rb
class CutElaborated < ApplicationRecord
  belongs_to :cut
  belongs_to :elaborated_product_name

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/cut_name.rb
class CutName < ApplicationRecord
  belongs_to :piece
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/mature_cut.rb
class MatureCut < ApplicationRecord
  belongs_to :cut

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  delegate :name, to: :piece_name

  belongs_to :quartering
  belongs_to :piece_name
end

app/models/piece_name.rb
class PieceName < ApplicationRecord
  belongs_to :family
end

app/models/quartering.rb
class Quartering < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cuts_controller.rb
class CutsController < ApplicationController
  before_action :set_cut, only: %i[ show edit update destroy ]

  def index
    @cuts = Cut.all
  end

  def show; end

  def new
    @cut = Cut.new
  end

  def edit; end

  def create
    @cut = Cut.new(cut_params)

    if @cut.save
      redirect_to cut_url(@cut), notice: "Cut was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @cut.update(cut_params)
      redirect_to cut_url(@cut), notice: "Cut was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @cut.destroy

    redirect_to cuts_url, notice: "Cut was successfully destroyed."
  end

  private

    def set_cut
      @cut = Cut.find(params[:id])
    end

    def cut_params
      params.require(:cut).permit(:piece_id, :cut_name_id, :weight, :final_weight, :processing_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/cut_names_helper.rb
module CutNamesHelper
end

app/helpers/cuts_helper.rb
module CutsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mature_cuts_helper.rb
module MatureCutsHelper
end

app/helpers/piece_names_helper.rb
module PieceNamesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/cuts/_cut.html.erb
<div id="<%= dom_id cut %>">
  <p>
    <strong>Piece:</strong>
    <%= cut.piece_id %>
  </p>

  <p>
    <strong>Cut name:</strong>
    <%= cut.cut_name_id %>
  </p>

  <p>
    <strong>Weight:</strong>
    <%= cut.weight %>
  </p>

  <p>
    <strong>Final weight:</strong>
    <%= cut.final_weight %>
  </p>

  <p>
    <strong>Processing type:</strong>
    <%= cut.processing_type %>
  </p>

  <%= link_to 'Madurado', new_mature_cut_path(cut_id: cut.id) %>
  <%= link_to 'Elaborado', new_cut_elaborated_path(cut_id: cut.id) %>
  <%= link_to 'Final', cut_elaborateds_path({ cut: { processing_type: 'FinalCut' } }), data: { 'turbo-method': :patch } %>
</div>

app/views/cuts/_form.html.erb
<%= form_with(model: cut) do |form| %>
  <% if cut.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cut.errors.count, "error") %> prohibited this cut from being saved:</h2>

      <ul>
        <% cut.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :piece_id, style: "display: block" %>
    <%= form.collection_select :piece_id, Piece.includes(:piece_name).all, :id, :name, { prompt: 'Seleccione la pieza'} %>
  </div>

  <div>
    <%= form.label :cut_name_id, style: "display: block" %>
    <%= form.collection_select :cut_name_id, CutName.order(:name), :id, :name, { prompt: 'Seleccione el nombre del corte'} %>
  </div>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :final_weight, style: "display: block" %>
    <%= form.number_field :final_weight %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cuts/edit.html.erb
<h1>Editing cut</h1>

<%= render "form", cut: @cut %>

<br>

<div>
  <%= link_to "Show this cut", @cut %> |
  <%= link_to "Back to cuts", cuts_path %>
</div>

app/views/cuts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cuts</h1>

<div id="cuts">
  <% @cuts.each do |cut| %>
    <%= render cut %>
    <p>
      <%= link_to "Show this cut", cut %>
    </p>
  <% end %>
</div>

<%= link_to "New cut", new_cut_path %>

app/views/cuts/new.html.erb
<h1>New cut</h1>

<%= render "form", cut: @cut %>

<br>

<div>
  <%= link_to "Back to cuts", cuts_path %>
</div>

app/views/cuts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cut %>

<div>
  <%= link_to "Edit this cut", edit_cut_path(@cut) %> |
  <%= link_to "Back to cuts", cuts_path %>

  <%= button_to "Destroy this cut", @cut, method: :delete %>
</div>