config/routes.rb
Rails.application.routes.draw do
  resources :cut_elaborateds
  resources :elaborated_product_names
  resources :mature_cuts
  resources :cuts
  resources :cut_names
  resources :pieces
  resources :piece_names
  resources :quarterings
  resources :channels
  resources :suppliers
  resources :families
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :family
  belongs_to :supplier
  belongs_to :user
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :piece
  belongs_to :cut_name
  has_one :mature_cut
  has_one :cut_elaborated

  def process
    case self.processing_type
    when 'MatureCut'
      self.mature_cut
    when 'CutElaborated'
      self.cut_elaborated
    when 'FinalCut'
      self
    else
      nil
    end
  end
end

app/models/cut_elaborated.rb
class CutElaborated < ApplicationRecord
  belongs_to :cut
  belongs_to :elaborated_product_name

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/cut_name.rb
class CutName < ApplicationRecord
  belongs_to :piece
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/mature_cut.rb
class MatureCut < ApplicationRecord
  belongs_to :cut

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  delegate :name, to: :piece_name

  belongs_to :quartering
  belongs_to :piece_name
end

app/models/piece_name.rb
class PieceName < ApplicationRecord
  belongs_to :family
end

app/models/quartering.rb
class Quartering < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cut_names_controller.rb
class CutNamesController < ApplicationController
  before_action :set_cut_name, only: %i[ show edit update destroy ]

  # GET /cut_names or /cut_names.json
  def index
    @cut_names = CutName.all
  end

  # GET /cut_names/1 or /cut_names/1.json
  def show
  end

  # GET /cut_names/new
  def new
    @cut_name = CutName.new
  end

  # GET /cut_names/1/edit
  def edit
  end

  # POST /cut_names or /cut_names.json
  def create
    @cut_name = CutName.new(cut_name_params)

    respond_to do |format|
      if @cut_name.save
        format.html { redirect_to cut_name_url(@cut_name), notice: "Cut name was successfully created." }
        format.json { render :show, status: :created, location: @cut_name }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cut_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cut_names/1 or /cut_names/1.json
  def update
    respond_to do |format|
      if @cut_name.update(cut_name_params)
        format.html { redirect_to cut_name_url(@cut_name), notice: "Cut name was successfully updated." }
        format.json { render :show, status: :ok, location: @cut_name }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cut_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cut_names/1 or /cut_names/1.json
  def destroy
    @cut_name.destroy

    respond_to do |format|
      format.html { redirect_to cut_names_url, notice: "Cut name was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cut_name
      @cut_name = CutName.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cut_name_params
      params.require(:cut_name).permit(:name, :piece_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/cut_names_helper.rb
module CutNamesHelper
end

app/helpers/cuts_helper.rb
module CutsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mature_cuts_helper.rb
module MatureCutsHelper
end

app/helpers/piece_names_helper.rb
module PieceNamesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/cut_names/_cut_name.html.erb
<div id="<%= dom_id cut_name %>">
  <p>
    <strong>Name:</strong>
    <%= cut_name.name %>
  </p>

  <p>
    <strong>Piece:</strong>
    <%= cut_name.piece_id %>
  </p>

</div>

app/views/cut_names/_form.html.erb
<%= form_with(model: cut_name) do |form| %>
  <% if cut_name.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cut_name.errors.count, "error") %> prohibited this cut_name from being saved:</h2>

      <ul>
        <% cut_name.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :piece_id, style: "display: block" %>
    <%= form.collection_select :piece_id, Piece.includes(:piece_name).all, :id, :name, { prompt: 'Seleccione la pieza'} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cut_names/edit.html.erb
<h1>Editing cut name</h1>

<%= render "form", cut_name: @cut_name %>

<br>

<div>
  <%= link_to "Show this cut name", @cut_name %> |
  <%= link_to "Back to cut names", cut_names_path %>
</div>

app/views/cut_names/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cut names</h1>

<div id="cut_names">
  <% @cut_names.each do |cut_name| %>
    <%= render cut_name %>
    <p>
      <%= link_to "Show this cut name", cut_name %>
    </p>
  <% end %>
</div>

<%= link_to "New cut name", new_cut_name_path %>

app/views/cut_names/new.html.erb
<h1>New cut name</h1>

<%= render "form", cut_name: @cut_name %>

<br>

<div>
  <%= link_to "Back to cut names", cut_names_path %>
</div>

app/views/cut_names/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cut_name %>

<div>
  <%= link_to "Edit this cut name", edit_cut_name_path(@cut_name) %> |
  <%= link_to "Back to cut names", cut_names_path %>

  <%= button_to "Destroy this cut name", @cut_name, method: :delete %>
</div>