config/routes.rb
Rails.application.routes.draw do
  resources :cut_elaborateds
  resources :elaborated_product_names
  resources :mature_cuts
  resources :cuts
  resources :cut_names
  resources :pieces
  resources :piece_names
  resources :quarterings
  resources :channels
  resources :suppliers
  resources :families
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :family
  belongs_to :supplier
  belongs_to :user
end

app/models/cut.rb
class Cut < ApplicationRecord
  belongs_to :piece
  belongs_to :cut_name
  has_one :mature_cut
  has_one :cut_elaborated

  def process
    case self.processing_type
    when 'MatureCut'
      self.mature_cut
    when 'CutElaborated'
      self.cut_elaborated
    when 'FinalCut'
      self
    else
      nil
    end
  end
end

app/models/cut_elaborated.rb
class CutElaborated < ApplicationRecord
  belongs_to :cut
  belongs_to :elaborated_product_name

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/cut_name.rb
class CutName < ApplicationRecord
  belongs_to :piece
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/mature_cut.rb
class MatureCut < ApplicationRecord
  belongs_to :cut

  after_create :set_process

  def set_process
    self.cut.update(processing_type: self.class.to_s)
  end
end

app/models/piece.rb
class Piece < ApplicationRecord
  delegate :name, to: :piece_name

  belongs_to :quartering
  belongs_to :piece_name
end

app/models/piece_name.rb
class PieceName < ApplicationRecord
  belongs_to :family
end

app/models/quartering.rb
class Quartering < ApplicationRecord
  belongs_to :channel
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cut_elaborateds_controller.rb
class CutElaboratedsController < ApplicationController
  before_action :set_cut_elaborated, only: %i[ show edit update destroy ]

  # GET /cut_elaborateds or /cut_elaborateds.json
  def index
    @cut_elaborateds = CutElaborated.all
  end

  # GET /cut_elaborateds/1 or /cut_elaborateds/1.json
  def show
  end

  # GET /cut_elaborateds/new
  def new
    @cut_elaborated = CutElaborated.new
  end

  # GET /cut_elaborateds/1/edit
  def edit
  end

  # POST /cut_elaborateds or /cut_elaborateds.json
  def create
    @cut_elaborated = CutElaborated.new(cut_elaborated_params)

    respond_to do |format|
      if @cut_elaborated.save
        format.html { redirect_to cut_elaborated_url(@cut_elaborated), notice: "Cut elaborated was successfully created." }
        format.json { render :show, status: :created, location: @cut_elaborated }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cut_elaborated.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cut_elaborateds/1 or /cut_elaborateds/1.json
  def update
    respond_to do |format|
      if @cut_elaborated.update(cut_elaborated_params)
        format.html { redirect_to cut_elaborated_url(@cut_elaborated), notice: "Cut elaborated was successfully updated." }
        format.json { render :show, status: :ok, location: @cut_elaborated }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cut_elaborated.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cut_elaborateds/1 or /cut_elaborateds/1.json
  def destroy
    @cut_elaborated.destroy

    respond_to do |format|
      format.html { redirect_to cut_elaborateds_url, notice: "Cut elaborated was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cut_elaborated
      @cut_elaborated = CutElaborated.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cut_elaborated_params
      params.require(:cut_elaborated).permit(:cut_id, :elaborated_product_name_id, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/cut_elaborateds_helper.rb
module CutElaboratedsHelper
end

app/helpers/cut_names_helper.rb
module CutNamesHelper
end

app/helpers/cuts_helper.rb
module CutsHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mature_cuts_helper.rb
module MatureCutsHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/cut_elaborateds/_cut_elaborated.html.erb
<div id="<%= dom_id cut_elaborated %>">
  <p>
    <strong>Cut:</strong>
    <%= cut_elaborated.cut_id %>
  </p>

  <p>
    <strong>Elaborated product name:</strong>
    <%= cut_elaborated.elaborated_product_name_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= cut_elaborated.description %>
  </p>

</div>

app/views/cut_elaborateds/_form.html.erb
<%= form_with(model: cut_elaborated) do |form| %>
  <% if cut_elaborated.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cut_elaborated.errors.count, "error") %> prohibited this cut_elaborated from being saved:</h2>

      <ul>
        <% cut_elaborated.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :cut_id %>
  </div>

  <div>
    <%= form.label :elaborated_product_name_id, style: "display: block" %>
    <%= form.collection_select :elaborated_product_name_id, ElaboratedProductName.order(:name), :id, :name, { prompt: 'Seleccione el nombre del producto eleborado' } %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cut_elaborateds/edit.html.erb
<h1>Editing cut elaborated</h1>

<%= render "form", cut_elaborated: @cut_elaborated %>

<br>

<div>
  <%= link_to "Show this cut elaborated", @cut_elaborated %> |
  <%= link_to "Back to cut elaborateds", cut_elaborateds_path %>
</div>

app/views/cut_elaborateds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cut elaborateds</h1>

<div id="cut_elaborateds">
  <% @cut_elaborateds.each do |cut_elaborated| %>
    <%= render cut_elaborated %>
    <p>
      <%= link_to "Show this cut elaborated", cut_elaborated %>
    </p>
  <% end %>
</div>

<%= link_to "New cut elaborated", new_cut_elaborated_path %>

app/views/cut_elaborateds/new.html.erb
<h1>New cut elaborated</h1>

<%= render "form", cut_elaborated: @cut_elaborated %>

<br>

<div>
  <%= link_to "Back to cut elaborateds", cut_elaborateds_path %>
</div>

app/views/cut_elaborateds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cut_elaborated %>

<div>
  <%= link_to "Edit this cut elaborated", edit_cut_elaborated_path(@cut_elaborated) %> |
  <%= link_to "Back to cut elaborateds", cut_elaborateds_path %>

  <%= button_to "Destroy this cut elaborated", @cut_elaborated, method: :delete %>
</div>